### ISSUE TITLE
TaskItem component performance

### ISSUE THREAD

**Issue by artemkolotilkin** [r-park/todo-react-redux#12]
Hi Richard,

First of all thanks for a great example that you put together. It provides a solid base to start building apps with React/Redux/Firebase. Which I did...

In my use case I'm looking to have a few thousand of components on one page and wanted to check how React can handle all of them. So I wrote a script that generated 5000 records in Firebase and was waiting for this data to magically appear on /tasks page. When the script ran my page froze and became unresponsive for some time and then crashed. I couldn't load it after that, so I deleted those records and reduced test set to 500 items. Even with a smaller set first load of the page takes ~15-30 seconds. If after that I run a script to generate another 500 records, the page freezes for another 15-30 seconds.

First I thought that the component is "heavy" and so removed all the inputs and SVGs from it, leaving basically just a title text. But it didn't give any performance increase.

So I'm just wondering if it's an expected behavior and this stack can only handle a limited set of data? Or is it an issue somewhere?

I'm pretty new to React/Redux world so it's hard for me to investigate it myself.

Again, thanks a lot for the effort of putting it all together! I hope we can tackle this performance issue as well.

**Comment by r-park** [comment]
Hi @artemkolotilkin – I'm glad you found this repo to be useful. 

Currently this project isn't really optimized for performance, especially for use-cases like yours. I would suggest you begin by looking at two areas.

1) Currently tasks are loaded and processed one at a time via the `child_added` callback, as you can [see here](https://github.com/r-park/todo-react-redux/blob/master/src/modules/tasks/actions.js#L85). You can investigate introducing the `value` callback as [shown here](https://github.com/r-park/todo-react-redux/blob/dev/src/modules/tasks/actions.js#L114) — this callback triggers when all items have been retrieved from firebase. Definitely check out the [official Firebase API docs](https://www.firebase.com/docs/web/api/query/on.html) for details.

2) Investigate React's `shouldComponentUpdate()` method:
> Use this as an opportunity to return false when you're certain that the transition to the new props and state will not require a component update.

You can find details in the [React docs here](https://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate), and an example in the [dev branch](https://github.com/r-park/todo-react-redux/blob/dev/src/components/tasks/task-item.js#L25) of this repo.

The dev branch is pointing to a firebase backend containing 500 task items.

**Comment by artemkolotilkin** [comment]
Thanks @r-park! I'll check this out today.

**Comment by artemkolotilkin** [comment]
Hi @r-park, I've just run some tests on the example branch and it works much faster. Thanks a lot for provided code! I'll use the same approach in my app. 
If I come up with any additional enhancements, I'll create a pull request to contribute them back.
Have a great weekend!

**Comment by r-park** [comment]
:+1:
