### ISSUE TITLE
Can't build: TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by simoneduca** [r-park/todo-react-redux#14]
Node v 4.1.2
Gulp v 4
![screen shot 2016-01-26 at 11 19 33](https://cloud.githubusercontent.com/assets/8989606/12579329/1091607e-c41f-11e5-8cc9-e628e7f317b6.png)

**Comment by r-park** [comment]
Hi @simoneduca 
Do you have gulp v3.x installed under `/usr/local/lib/node_modules/gulp` (from your screenshot)? If so, were you trying to run the `gulp` command globally via:
```
$ gulp
```
or via the project-local version from within `~/Documents/Projects/todo-react-readux/`
```
$ ./node_modules/.bin/gulp
```

**Comment by simoneduca** [comment]
Ah running the latter command did it, thanks. (I also had to rebuild node-sass)

**Comment by r-park** [comment]
:+1:
