### ISSUE TITLE
Auth doesn't appear to work after deploying to my own account.

### ISSUE THREAD

**Issue by andysprout** [r-park/todo-react-redux#27]
I have:

- checked out the source code
- `npm install -g firebase-tools` (installs version 3.0.0)
- created a firebase account
- created a firebase project
- enabled google, github and twitter auth on the firebase console (creating github and twitter apps for oauth)
- changed `FIREBASE_URL` in `src/config.js` to `https://<myproject>.firebaseio.com`
- `npm install && npm run build` from the project dir
- `firebase deploy`

I get a serious of errors about some deprecated features in `./firebase.json` once I fix those though it deploys, but when I click any of the authenticate links, I get an Authentication Disabled error even though I have definitely enabled all three auth providers on the dashboard.

<img width="635" alt="screenshot 2016-05-22 14 42 26" src="https://cloud.githubusercontent.com/assets/132021/15452255/7a574b6e-202b-11e6-8519-c552b5992475.png">

Could this be because I am trying to deploy with version 3.0.0 of the firebase tools?

**Comment by andysprout** [comment]
I reverted to `firebase-tools@2.2.1` and I can now deploy. It's confusing that even the dashboard and the routes for the dashboard have changed from v2 -> v3 so there was no way of knowing that the app I created would not be compatible with a v2 app.

**Comment by r-park** [comment]
@andysprout Firebase v3 introduced a number of breaking changes — currently this repo only supports v2.

**Comment by andysprout** [comment]
Sorry I am very new to firebase, this was the first firebase project I tried to deploy, so it wasn't clear that it would only work with version 2 of firebase-tools. Not sure how much effort is involved in #26 but let me know if you think I can help out. Thank for the creating the project it really helped me understand some of the features of firebase.
