### ISSUE TITLE
Google Authentication not working with v3 Firebase upgrade

### ISSUE THREAD

**Issue by witnessmenow** [r-park/todo-react-redux#30]
Even on https://todo-react-redux.firebaseapp.com/sign-in I get this as well

![screen shot 2016-05-23 at 10 11 50](https://cloud.githubusercontent.com/assets/1562562/15465937/f6c252ae-20ce-11e6-8cfe-2d72b4b06606.png)

**Comment by r-park** [comment]
Thanks @witnessmenow — should be working now

**Comment by witnessmenow** [comment]
@r-park Ha! I was literally showing it to someone there and it worked and came back to check here and your post was 19 seconds old, what timing!

What change did you make?

**Comment by r-park** [comment]
Needed to fix some of the OAuth settings on the Google side (https://console.developers.google.com). The automated firebase migration process seems to have generated new OAuth client id and key without telling me.
