### ISSUE TITLE
Adding new route

### ISSUE THREAD

**Issue by lvtrvd** [r-park/todo-react-redux#31]
When I am adding a new route its by default redirecting to the task route again
when I comment the else part of route-resolver 
 ```
 else if (auth.authenticated && `/${pathname}` !== POST_SIGN_IN_PATH) {
      //replace({pathname: POST_SIGN_IN_PATH});
    }
```
than its working but page is reloading whenever I change the route.

please suggest a suitable solution

**Comment by r-park** [comment]
@lvtrvd take a look at this example branch: https://github.com/r-park/todo-react-redux/tree/issue-31

**Comment by lvtrvd** [comment]
Thanks for your support, its working fine 
 I have a query also, How can I redirect or change route with onClick function
like in flux or normal redux I can use history.pushState(null, /path)
is there any suitable way to do this in component

Thanks for your support

**Comment by r-park** [comment]
The easiest way to navigate routes `onClick` is to use the `<Link />` component from react-router.
```javascript
import { Link } from 'react-router';

<Link to="/">Home</Link>
```
You can also gain access to the `router` itself via component context:
```javascript
export class MyComponent extends Component {
  static contextTypes = {
    router: React.PropTypes.object.isRequired
  };

  handleClick() {
    this.context.router.push('/users/12')
  }
}
```

**Comment by lvtrvd** [comment]
Thanks for your support
its working fine now.
