### ISSUE TITLE
redux reducers and actions?

### ISSUE THREAD

**Issue by ginxwar** [r-park/todo-react-redux#33]
I may be missing something huge, but I'm unable to locate where you are using redux reducers and actions.

**Comment by r-park** [comment]
- For tasks, the state and actions are connected to the `Task` component [here](https://github.com/r-park/todo-react-redux/blob/master/src/components/tasks/tasks.js#L79).
- Thunked actions like [createTask](https://github.com/r-park/todo-react-redux/blob/master/src/core/tasks/actions.js#L12) submit requests to Firebase. 
- Firebase [listeners](https://github.com/r-park/todo-react-redux/blob/master/src/core/tasks/actions.js#L81) are setup to dispatch responses to the tasks reducer.
