### ISSUE TITLE
React hot loader not working

### ISSUE THREAD

**Issue by nbikar** [r-park/todo-react-redux#36]
I cloned your repo. When, making a change, there is no hot loading.

**Comment by r-park** [comment]
Hi @nbikar — did you receive an error or any other output in the console?

**Comment by nbikar** [comment]
There is no error or output in the console. However, if I change anything in the files, there is no recompilation and view doesn' get updated.

**Comment by r-park** [comment]
That's strange — your browser console should display the following messages when you load the app:

![screen shot 2016-07-03 at 9 44 55 pm](https://cloud.githubusercontent.com/assets/6252638/16549006/e96a6d26-4167-11e6-85d2-6a548a81d8bd.png)

Are you starting the app via `npm start` ?

**Comment by nbikar** [comment]
This is what I see. Yes. I am using npm start

![image](https://cloud.githubusercontent.com/assets/20155078/16574217/5ff4f85c-4231-11e6-855a-e9a08cbe1e02.png)
