### ISSUE TITLE
Using ejs, the build keeps trying to compile templates in build process

### ISSUE THREAD

**Issue by morgs32** [r-park/todo-react-redux#47]
I'm not sure why the ejs loader (default for htmlwebplugin) is trying to render the template in the build process. It gets added to the target directory rendering the error, something along the lines of `variable not defined`.

Let me know if I should share my whole webpack config. Mostly the changes are this:
```
 new HtmlWebpackPlugin({
      filename: './server/views/index.ejs',
      hash: true,
      inject: 'body',
      template: './server/views/index.ejs'
      // template: './src/index.html'
    })
```

and this:
```
  config.module = {
    loaders: [
      loaders.js,
      loaders.scss,
      {
        test: /\.ejs$/,
        loader: 'ejs-loader'
      }
    ]
  };
```

Thanks

**Comment by r-park** [comment]
Hey @morgs32 — I'm not sure I'm understanding your question. Can you describe the end result you're trying to achieve?

**Comment by morgs32** [comment]
That does help explain a little - I've been at this a long time and gathered that. But you're absolutely right I should describe better what I'm trying to do. I'll do that in a new issue. Thanks.
