### ISSUE TITLE
How would you go about moving this to webpack-dev-middleware in express

### ISSUE THREAD

**Issue by morgs32** [r-park/todo-react-redux#48]
I need to use the express server to provide just one or two API endpoints that can't be served by firebase (to talk to Twilio or some other API). I'm have a very tough time doing so. 
I've forked your repo (which is epic by the way) and am trying to do that with this commit:
https://github.com/morgs32/morgans-tt/commit/25d90e5ecdd876d9754d1ebe583ccab3a0b86bae

From what I understand, the htmlwebpackplugin stores the compiled index.html file in memory. So I think the question is, how to get it with `res.sendFile`?

**Comment by r-park** [comment]
Have you tried this: https://github.com/ampedandwired/html-webpack-plugin/issues/145#issuecomment-170554832

**Comment by morgs32** [comment]
Aww I must have been in that repo for hours. But maybe I'm going cross-eyed. I've got one more question - not blocking me but I'd love to see what you think...
