### ISSUE TITLE
How to preserve ejs templating so can isomorphically render

### ISSUE THREAD

**Issue by morgs32** [r-park/todo-react-redux#49]
Hi again,

So here is my other question. I'd like to go isomorphic with your starter. This means using ejs (or any other templating language I presume). However, again htmlwebpackplugin gets in the way. It wants to compile the template (with lodash/underscore) as part of the webpack. I need it to leave the ejs templating language alone, so I can have it in the build.

Any thoughts?

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/1364795/17085490/59502d20-51a7-11e6-82b9-adbc11b084cf.png)

And here's the place in my commit where I isomorphically get the html.
https://github.com/morgs32/morgans-tt/blob/master/server/main.js#L116

Thanks man. If you put one of those "buy me a coffee" widgets in the readme i'd use it in a heartbeat. but i know that's not for everyone.

**Comment by morgs32** [comment]
To clarify, the reason this isn't a deal breaker is because I still use the index.html to in dev. The one at `src/index.html`. I just flat out ignore the one that gets put into `target/index.html` when running this in prod. Which means if I ever want to add analytics scripts, etc, to the index.html/ejs I've got to duplicate it.
So, it's not a blocker. But it kept me up last night, that's all!

**Comment by r-park** [comment]
@morgs32 since you're [reading](https://github.com/morgs32/morgans-tt/blob/master/server/main.js#L88) the build artifacts from `./target` and manually injecting them into the `index.ejs`, you don't really need `HtmlWebpackPlugin`.
