### ISSUE TITLE
How are you resolving 'src/core/auth'?

### ISSUE THREAD

**Issue by cameronroe** [r-park/todo-react-redux#56]
I don't see any webpack config resolving imports like `src/core/auth`. How are you resolving that?

**Comment by r-park** [comment]
Hi @cameronroe 

The project root [is set](https://github.com/r-park/todo-react-redux/blob/master/webpack.config.js#L41) in `webpack.config.js`

**Comment by cameronroe** [comment]
Cool, thanks @r-park. I discovered I had my `resolve.root` set to the `src` directory, which then would use `core/auth` instead of `src/core/auth`. I prefer it that way considering that I mostly will only need to reference directories in the `src` dir. Cheers.
