### ISSUE TITLE
how to do an incremental build

### ISSUE THREAD

**Issue by ORESoftware** [r-park/todo-react-redux#60]
I am new to ES6 modules - the build for this project takes awhile, I am used to reloading the web app after making changes to client code :)

is there an easy way to do an _incremental_ build with WebPack for this project? Please let me know! thanks for this project!

**Comment by ORESoftware** [comment]
perhaps using 

`$ npm run dev`

instead of

`$ npm run build`

is good enough? probably :)

**Comment by r-park** [comment]
Hi @ORESoftware — yes, `npm run dev` (or `npm start`) will build incrementally 👍

**Comment by ORESoftware** [comment]
thanks! makes sense, and HMR is in place.

one issue I am having is that login is not working, 

if I click Google/Github/Twitter, I do not get directed to an OAuth page, never am logged in, and also, I never see any todo page!

I want to make some todos! I am not sure how to debug this problem. Do you have any ideas?

**Comment by ORESoftware** [comment]
my guess is my auth on my firebase account is not setup correctly

**Comment by ORESoftware** [comment]
yep, here is why

https://www.dropbox.com/s/zppbao47ddgoo40/Screenshot%202016-09-14%2019.14.58.png?dl=0

thanks anyway, you can close!
